name: Build Flutter APK

on:
  workflow_dispatch: # Habilita un botón para ejecutar el proceso manualmente

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fundamental para descargar los forks de third_party/

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Obtener dependencias de Flutter
        run: flutter pub get
         
      
      - name: Generar iconos automaticamente
        run: flutter pub run flutter_launcher_icons

      - name: Compilar APK (Solo 64 bits)
        run: flutter build apk --release --split-per-abi

      - name: Subir APK de 64 bits como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/app/outputs/flutter-apk/*.apk
